kind: Service
apiVersion: v1
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  # perlu diingat, walaupun disini pake ClusterIP, ip nya akan tetap stabil dan tidak berubah
  type: ClusterIP
  ports:
    - name: auth-port
      port: 80
      targetPort: 80
