kind: Service
apiVersion: v1
metadata:
  name: users-service
spec:
  selector:
    app: users
  type: LoadBalancer
  ports:
    - name: users-port
      port: 8080
      targetPort: 8080
# DISINI UNTUK BERKOMUNIKASI DENGAN APLIKASI DI POD YANG SAMA, CUKUP GUNAKAN LOCALHOST SAJA YAH, GAK PERLU PAKE PORT!!!, JADI KALO KOMUNIKASI INTERNAL POD GAK PERLU EXPOSE KELUAR
